### ISSUE TITLE
Alignment output file

### ISSUE THREAD

**Issue by vijay-naidu** [albertozeni/LOGAN#7]
Hello fellow researchers,

Great algorithm. Just managed to compile and run the X-drop alignment algorithm. It's so fast!!
Just curious. Can I align any two nucleotide sequences and output the alignment in a fasta or any other alignment format?
I see that it's a part of BELLA algorithm but eager to know if LOGAN can be used as a standalone tool for performing pairwise alignment?
This is not an issue but a query.

Many Thanks,
Vijay

**Comment by albertozeni** [comment]
Hi Vijay,
Xdrop is already a standalone aligner, 
You can use it to replace any aligner that performs operations similar to Needleman-Wunsch.
The software mirrors SeqAn Xdrop implementation, 
as such it outputs seeds containing info regarding the alignment boundaries and the alignment score.
By any alignment format, do you mean something like BAM or SAM? 
It would be helpful to know where do you want to use Xdrop.

Ciao,
Alberto

**Comment by vijay-naidu** [comment]
Hi Alberto,

Thanks for getting back to me. I am looking for global pairwise sequence alignment (using NWA) and something similar to Emboss Stretcher (https://www.ebi.ac.uk/Tools/psa/emboss_stretcher/) or Emboss Needle (https://www.ebi.ac.uk/Tools/psa/emboss_needle/). I am specifically looking for alignment formats, such as Pearson/Fasta or ClustalW. BAM or SAM is fine too as I can convert them into fasta format.

Best Regards,
Vijay

**Comment by albertozeni** [comment]
Hi Vijay,

Sorry for the late reply but had a lot of work to do by the end of the year.
I don't have time currently for applying that feature,
I'll look into implement that in the following months,
I'll get back to you when this will be implemented.

Best,
Alberto

**Comment by vijay-naidu** [comment]
Hi Alberto,

No worries about that.
That would be wonderful.
Happy new year!!

Best Regards,
Vijay
